//==============================================================================
// File:           BootLdr.h
// Compiler:       IAR Atmel AVR C/EC++ Compiler
// Output Size:    -
// Created:        12/28/10
//
// Description:    This file is generated by 'create' tool and is to be included
//                 in the 'bootldr' project. It contains the settings to
//                 configure the boot loader according to the configurations
//                 used in the encrypted file.
//==============================================================================


#ifndef BOOTLDR_H
#define BOOTLDR_H


#define PAGE_SIZE 128
#define MEM_SIZE 13952
#define CRC_CHECK
#define SIGNATURE 	0x90311325		//0x25133190
#define BUFFER_SIZE 148
#define INITIALVECTOR_HI 0x286CCD07			//0x07CD6C28
#define INITIALVECTOR_LO 0x6DE808D9			//0xD908E86D
#define KEY_COUNT 1


#endif // BOOTLDR_H
